kind: pipeline
type: docker
name: build

steps:
- name: move-to-volume
  image: alpine:latest
  volumes:
  - name: site-oresundspacecollective
    path: /var/site
  commands:
    - ls /var/site
    - rm -rf /var/site/*
    - mv src/* /var/site
    - ls /var/site

trigger:
  event:
  - push