kind: pipeline
type: docker
name: build

steps:
- name: move-to-volume
  image: alpine:latest
  volumes:
  - name: site
    path: /tmp/site
  commands:
    - mkdir /tmp/site
    - ls /tmp/site
    - rm -rf /tmp/site/*
    - mv src/* /tmp/site
    - ls /tmp/site

volumes:
- name: site
  host:
    path: /var/sites/osc

trigger:
  event:
  - push