kind: pipeline
type: docker
name: build

steps:
- name: move-to-volume
  image: alpine:latest
  volumes:
  - name: site
    path: /tmp/site
  commands:
  #- rm -rf /tmp/site/*
  - mv src/* /tmp/site
- name: compress-images
  image: alpine:latest
  volumes:
  - name: site
    path: /tmp/site
  commands:
  - apk update
  - apk add jpegoptim
  - cd /tmp/site
  - find . -name "*.jpg" -exec jpegoptim --strip-all  {} \;
  - find . -name "*.jpeg" -exec jpegoptim --strip-all  {} \;

volumes:
- name: site
  host:
    path: /var/sites/osc

trigger:
  event:
  - push