kind: pipeline
type: docker
name: build

steps:
- name: move-to-volume
  image: alpine:latest
  volumes:
  - name: site
    path: /tmp/site
  commands:
  - rm -rf /tmp/site/*
  - mv src/* /tmp/site
- name: compress-images
  image: alpine:latest
  volumes:
  - name: site
    path: /tmp/site
  commands:
  - apk update
  - apk add jpegoptim
  - cd /tmp/site
  - find . -name '*.jpg' -o -name '*.jpeg' -exec jpegoptim --strip-all {} \;
- name: compress-css-and-js
  image: alpine:latest
  volumes:
  - name: site
    path: /tmp/site
  commands:
  - apk update
  - apk add npm
  - npm install uglify-js -g
  - npm install uglifycss -g
  - cd /tmp/site
  - find . -name '*.js' -exec uglifyjs --compress --mangle -- {} \;
  - find . -name '*.css' -exec uglifycss -- {} \;
- name: check-links
  image: python:3-alpine
  volumes:
  - name: site
    path: /tmp/site
  commands:
  - pip3 install linkchecker
  - find . -name '*.html' -o -name '*.htm' -exec linkchecker {} \;

volumes:
- name: site
  host:
    path: /var/sites/osc

trigger:
  event:
  - push