kind: pipeline
type: docker
name: default

steps:
  - name: rsync-copy
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      source: ./src/
      target: /var/www/oresundspacecollective/
      recursive: true
      #delete: true
