kind: pipeline
type: docker
name: build

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: osc
    tag: latest
    username:
      from_secret: registry-username
    password:
      from_secret: registry-password
    registry:
      from_secret: registry-url
    dockerfile: dockerfile
    platform: linux/amd64
  
trigger:
  event:
  - push