kind: pipeline
type: docker
name: build

steps:
- name: move-to-volume
  image: apline
  commands:
    - ls /var/site
    - rm -rf /var/site/*
    - mv src/* /var/site
    - ls /var/site
  
volumes:
- name: site-oresundspacecollective
  host:
    path: /var/site

trigger:
  event:
  - push