kind: pipeline
type: docker
name: build

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: osc
    tag: latest
    dockerfile: dockerfile
    platform: linux/amd64
  
trigger:
  event:
  - push