resource_types:
- name: lftp-resource
  type: docker-image
  source:
      repository: machinerytool/concourse-lftp-resource
      tag: latest

resources:
  - name: source-code
    type: git
    icon: github
    source:
      uri: https://github.com/oscar230/oresundspacecollective.com

  - name: ftp
    type: lftp-resource
    icon: save
    source:
      url: sftp://((sftp_username)):((sftp_password))@((sftp_host))/((sftp_path))

jobs:
  - name: deploy
    plan:
    - get: source-code
      trigger: true
    - put: ftp
      params:
        files: "source-code/*"