resource_types:
- name: s3-resource
  type: docker-image
  source:
    repository: concourse/s3-resource
    tag: latest

resources:
  - name: source-code
    type: git
    icon: github
    source:
      uri: https://github.com/oscar230/oresundspacecollective.com

  - name: s3
    type: s3-resource
    icon: save
    source:
      bucket: ((s3_bucket_name))
      access_key_id: ((s3_access_key))
      secret_access_key: ((s3_secret_key))
      endpoint: http://((s3_host))

jobs:
  - name: deploy
    plan:
    - get: source-code
      trigger: true
    - task: prepare
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
        inputs:
          - name: source-code
        outputs:
          - name: out
        run:
          path: sh
          args:
            - -exc
            - |
              mkdir -p out
              cp -r source-code/src/* out/
              tar -czvf out/archive.tar.gz -C out .

    - put: s3
      params:
        file: out/archive.tar.gz